

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001" 
    environment:

      - REDIS_HOST=redis 
      - REDIS_PORT=6379
      - APP_HOST=0.0.0.0
      - APP_PORT=8001 
    volumes:
      - ./base:/app/base
      - ./tenant_configs:/app/tenant_configs
      - ./api.log:/app/api.log
    depends_on:
      - redis 
    restart: unless-stopped 
  redis:
    image: redis:alpine 
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data: 
